name = "CategoricalTensorNetworks"
uuid = "b369e0ec-beea-4e3a-b4d0-cd2e7e44da01"
license = "MIT"
authors = ["Evan Patterson <evan@epatters.org>"]
version = "0.0.1"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"

[compat]
Catlab = "^0.16"
julia = "1.9"
